[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
game_2024 = "GRxJzSgBKJkgYRtjCzciCf1Pf68iGkygcH5s2RPvxj6Z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/tabatrung/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
